var d=0,e=[],f=!1,g=window.innerWidth/2,h=window.innerHeight/2+44;function k(){var a=document.getElementById("playerFrame").contentWindow;return void 0!==a.c?a.c.b.g(a.b):null}function l(a){var b=Math.floor(a%60);return Math.floor(a/60)+":"+(10>b?"0"+b:b)}
function m(){var a=k();if(void 0!==a&&null!==a){var b=a.h(),a=a.i();b.current>=b.duration?n():p('Now playing: <a href="https://www.youtube.com/watch?v='+a.o+'" target="_blank">'+(50<a.title.length?a.title.substring(0,50)+"...":a.title)+" ("+l(b.current)+" / "+l(b.duration)+")</a> <small>("+d+"/"+e.length+")</small>")}}
function q(){for(var a=document.getElementsByClassName("yt-lockup-thumbnail contains-addto"),b=0,c=0;c<a.length;c++)if(0<=a[c].getAttribute("class").indexOf("watched")){if(b++,3<=b)break}else b=0;2>=b?(p("Loading more videos... ("+a.length+")"),a=document.getElementsByClassName("load-more-button"),0<a.length?(a[0].click(),setTimeout(q,1E3)):r()):r()}
function t(){var a=document.getElementById("pauseButton");a.style.backgroundImage="url('https://raw.githubusercontent.com/google/material-design-icons/master/av/1x_web/ic_play_arrow_white_24dp.png')";a.onclick=function(){u()};f=!0;k().l()}
function u(){if(f){var a=document.getElementById("pauseButton");a.style.backgroundImage="url('https://raw.githubusercontent.com/google/material-design-icons/master/av/1x_web/ic_pause_white_24dp.png')";a.onclick=function(){t()};f=!1;k().m()}else p("Can't resume if the video was never paused")}
function n(){if(0<=d){var a=e[d],b=document.getElementById("pauseButton");b.style.backgroundImage="url('https://raw.githubusercontent.com/google/material-design-icons/master/av/1x_web/ic_pause_white_24dp.png')";b.onclick=function(){t()};null===k()?document.getElementById("playerFrame").src="https://www.youtube.com/embed/"+a+"?autoplay=1&controls=0&enablejsapi=1":k().j(a);d--}else p("All vids watched - removing embedded controls"),v()}
function p(a){var b=document.getElementById("statusLabel");null!=b&&(b.innerHTML=a)}function v(){var a=document.getElementById("playControls");a.parentNode.removeChild(a)}
function r(){for(var a=document.getElementsByClassName("yt-lockup-thumbnail contains-addto"),b=0;b<a.length;b++)if(0>a[b].getAttribute("class").indexOf("watched")){var c=a[b].firstChild.getAttribute("href"),c=c.substring(c.indexOf("?")+3);p("Adding vid: "+c);e[e.length]=c}0<e.length?(d=e.length-1,a=document.createElement("div"),a.style.width=g+"px",a.style.height=h-34+"px",a.style.marginTop="34px",a.style.position="absolute",document.getElementById("playControls").appendChild(a),a=document.createElement("iframe"),
a.style.width=g+"px",a.style.height=h-34+"px",a.id="playerFrame",a.f="0",a.src="",document.getElementById("playControls").appendChild(a),n(),setInterval(m,1E3)):(alert("No videos to watch!"),v())}
(function(){var a=document.createElement("div");a.id="playControls";a.style.width=g+"px";a.style.height=h+"px";a.style.top="0px";a.style.marginLeft=window.innerWidth/2-g/2+"px";a.style.marginRight="auto";a.style.marginTop=window.innerHeight/2-h/2+"px";a.style.position="fixed";a.style.border="1px solid #888";a.style.borderRadius="5px";a.style.zIndex="9999999999";a.style.backgroundColor="rgba(0,0,0,0.8)";a.style.padding="10px";a.style.color="#fff";var b=document.createElement("div");b.style.backgroundImage=
"url('https://raw.githubusercontent.com/google/material-design-icons/master/navigation/1x_web/ic_chevron_left_white_24dp.png')";b.style.width="24px";b.style.height="24px";b.style.a="left";b.style.marginBottom="10px";b.onclick=function(){d+2>=e.length?p("Can't go back any further, please load more videos to go back further"):(d+=2,n())};a.appendChild(b);b=document.createElement("div");b.id="pauseButton";b.style.backgroundImage="url('https://raw.githubusercontent.com/google/material-design-icons/master/av/1x_web/ic_play_arrow_white_24dp.png')";
b.style.width="24px";b.style.height="24px";b.style.a="left";b.onclick=function(){t()};a.appendChild(b);b=document.createElement("div");b.style.backgroundImage="url('https://raw.githubusercontent.com/google/material-design-icons/master/navigation/1x_web/ic_chevron_right_white_24dp.png')";b.style.width="24px";b.style.height="24px";b.style.a="left";b.onclick=function(){n()};a.appendChild(b);b=document.createElement("b");b.id="statusLabel";b.style.a="left";b.style.lineHeight="24px";a.appendChild(b);document.getElementsByTagName("body")[0].appendChild(a)})();
q();